---------------------------------------------------------------------------
--- This module documentation has been merged with the `mouse` module.
--
-- @module awful.mouse
---------------------------------------------------------------------------
