---------------------------------------------------------------------------
--- This module documentation has been merged with the `screen` class.
--
-- @module awful.screen
---------------------------------------------------------------------------
