---------------------------------------------------------------------------
--- This module documentation has been merged with the `client` class.
--
-- @module awful.client
---------------------------------------------------------------------------
