---------------------------------------------------------------------------
--- This module documentation has been merged with the `client` module.
--
-- @module awful.client
---------------------------------------------------------------------------
