---------------------------------------------------------------------------
--- This module documentation has been merged with the `screen` module.
--
-- @module awful.screen
---------------------------------------------------------------------------
