#!/bin/sh

echo "/* This file is autogenerated by $0 - do not edit */"
echo

while read atom
do
    echo extern xcb_atom_t $atom\;
done < $1

# vim: filetype=sh:expandtab:shiftwidth=4:tabstop=8:softtabstop=4:textwidth=80
