#!/bin/sh
top_srcdir="${1-.}"
echo "/* This file is autogenerated by" $(basename $0) "*/"
echo
echo "const name_func_link_t LayoutList[] ="
echo "{"
for file in ${top_srcdir}/layouts/*.h
do
    echo "    /* $file */"
    grep '^LayoutArrange layout_' $file | cut -d' ' -f2 | cut -d\; -f1 | while read layout
    do
        shortname=$(echo $layout | cut -d _ -f2-)
        echo "    {\"$shortname\", $layout},"
    done
done

echo "    {NULL, NULL}"
echo "};"
