#!/bin/sh
top_srcdir="${1-.}"
echo "/* This file is autogenerated by" `basename $0` "*/"
echo
for file in ${top_srcdir}/layouts/*.h
do
    shortname=`echo $file | cut -f2- -d/`
    echo "#include \"${shortname}\""
done
echo
echo "const name_func_link_t LayoutList[] ="
echo "{"
for file in ${top_srcdir}/layouts/*.h
do
    echo "    /* $file */"
    grep '^layout_t layout_' $file | cut -d' ' -f2 | cut -d\; -f1 | while read layout
    do
        shortname=`echo $layout | cut -d _ -f2-`
        echo "    {\"$shortname\", sizeof(\"$shortname\") - 1, $layout},"
    done
done

echo "    {NULL, 0, NULL}"
echo "};"
