#!/bin/sh
# Syntax:
#   $0 <path-to-top_srcdir> <version-stamp-file>
#
# <path-to-top_srcdir> may be relative
# <version-stamp-file> is relative to src/build topdir

top_srcdir="${1-.}"
test -d "$top_srcdir" || { \
	echo "Could not change to top_srcdir '$1'" >&2; \
	exit 1; \
}
version_stamp="${2-version-stamp}"

if test -f "$top_srcdir/$version_stamp"; then # dist source tree
	cat "$top_srcdir/$version_stamp" | ${TR-tr} -d '\012'
elif test -d "$top_srcdir/.git"; then # git source tree
	git_describe=`${GIT-git} --git-dir="$top_srcdir/.git" describe 2>/dev/null || echo devel`
	echo "$git_describe" | ${SED-sed} -e 's/^v//' -e 's/-/./g' | ${TR-tr} -d '\012'
else # ???
	echo "devel" | ${TR-tr} -d '\012'
fi
