#!/bin/sh
# Syntax:
#   $0 <path-to-top_srcdir> <codename-stamp-file>
#
# <path-to-top_srcdir> may be relative
# <codename-stamp-file> is relative to src/build topdir

top_srcdir="${1-.}"
test -d "$top_srcdir" || { \
	echo "Could not change to top_srcdir '$1'" >&2; \
	exit 1; \
}
codename_stamp="${2-codename-stamp}"

if test -f "$top_srcdir/$codename_stamp"; then # dist source tree
	echo \"$(cat "$top_srcdir/$codename_stamp" | ${TR-tr} -d '\012')\"
else
	echo \""Productivity Breaker"\" | ${TR-tr} -d '\012'
fi
