#!/bin/sh
echo "/* This file is autogenerated by" $(basename $0) "*/"
echo
echo "const name_func_link_t WidgetList[] ="
echo "{"
for file in widget.h
do
    echo "    /* $file */"
    grep '^WidgetConstructor ' widget.h | cut -d' ' -f2 | cut -d\; -f1 | while read widget
    do
        shortname=$(echo $widget | cut -d_ -f1)
        echo "    {\"$shortname\", $widget},"
        grep -q "^$shortname" awesomerc.1.txt || \
            echo "  WARNING: $uicb NOT documented" >&2
    done
done

echo "    {NULL, NULL}"
echo "};"
