pull_request_rules:
  - name: automatic merge
    conditions:
      - label!=no-mergify
      - '#approved-reviews-by>=2'
      - status-success=Build & Test
      - status-success=Update API docs
      - status-success=codecov/patch
    actions:
      merge:
        method: merge
      delete_head_branch: {}
      dismiss_reviews: {}
