rules:
  default:
    protection:
      required_status_checks:
        contexts:
          - continuous-integration/travis-ci
          - Codacy/PR Quality Review
          - codecov/patch
          - coverage/coveralls
      required_pull_request_reviews:
        required_approving_review_count: 2
