#ifndef _AWE_VERSION_INTERNAL_H_
#define _AWE_VERSION_INTERNAL_H_

#define AWESOME_VERSION             "@AWESOME_VERSION@"
#define AWESOME_RELEASE             "@AWESOME_RELEASE@"

#endif //_AWE_VERSION_INTERNAL_H_
