#ifndef _AWE_VERSION_INTERNAL_H_
#define _AWE_VERSION_INTERNAL_H_

#define AWESOME_VERSION             "@AWESOME_VERSION@"
#define AWESOME_COMPILE_MACHINE     "@AWESOME_COMPILE_MACHINE@"
#define AWESOME_COMPILE_BY          "@AWESOME_COMPILE_BY@"
#define AWESOME_COMPILE_HOSTNAME    "@AWESOME_COMPILE_HOSTNAME@"
#define AWESOME_RELEASE             "@AWESOME_RELEASE@"

#endif //_AWE_VERSION_INTERNAL_H_
