STRING(REGEX REPLACE "v([0-9.]+)-(.*)$"
	"\\1;\\2" VERSION_RESULT ${VERSION})

LIST(GET VERSION_RESULT 0 VERSION_NUM)
LIST(GET VERSION_RESULT 1 VERSION_GITSTAMP)

STRING(REGEX REPLACE "([0-9]+)\\.([0-9]+)\\.([0-9]+)"
	"\\1;\\2;\\3" VERSION_NUM_SPLIT ${VERSION_NUM})

LIST(GET VERSION_NUM_SPLIT 0 CPACK_PACKAGE_VERSION_MAJOR)
LIST(GET VERSION_NUM_SPLIT 1 CPACK_PACKAGE_VERSION_MINOR)
LIST(GET VERSION_NUM_SPLIT 2 CPACK_PACKAGE_VERSION_PATCH)

SET(CPACK_PACKAGE_VERSION "${VERSION_NUM}~git${VERSION_GITSTAMP}")
SET(CPACK_DEBIAN_PACKAGE_VERSION "${VERSION_NUM}~git${VERSION_GITSTAMP}")

SET(CPACK_GENERATOR "DEB")
SET(CPACK_PACKAGE_NAME "awesome")
SET(CPACK_DEBIAN_PACKAGE_ARCHITECTURE "amd64")
SET(CPACK_DEBIAN_PACKAGE_MAINTAINER "devnull@example.com")
SET(CPACK_PACKAGE_DESCRIPTION_SUMMARY "A tiling window manager")

INCLUDE(CPack)
